"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.1.
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

import cloudinary
import dj_database_url
from django.core.exceptions import ImproperlyConfigured


# =========================================================
# BASE DIRECTORY
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# LOAD .ENV
# =========================================================

# Real environment variables (shell, CI, hosting) win over the
# local `.env` file, so a deployment cannot be silently
# overridden by a checked-out development file.

load_dotenv(
    BASE_DIR / '.env',
    override=False
)


# =========================================================
# SECURITY
# =========================================================

# A deployment sets DJANGO_ENV=production. Everywhere else DEBUG
# stays on so a fresh clone runs with `manage.py runserver`
# without extra configuration, and can still be turned off
# explicitly by setting DEBUG=False in .env.

DJANGO_ENV = os.getenv(
    'DJANGO_ENV',
    'development'
).lower()


SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-development-key'
)


DEBUG = os.getenv(
    'DEBUG',
    'True' if DJANGO_ENV != 'production' else 'False'
).lower() == 'true'


# Hosts are configurable so a new deployment does not need a code change.
# A safe local default is used when the variable is missing.

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        'ALLOWED_HOSTS',
        '127.0.0.1,localhost,'
        'studybuddy-9bug.onrender.com,'
        'studybuddyapp.in.net'
    ).split(',')
    if host.strip()
]


# =========================================================
# CSRF
# =========================================================

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        'CSRF_TRUSTED_ORIGINS',
        'https://studybuddy-9bug.onrender.com,'
        'https://studybuddyapp.in.net'
    ).split(',')
    if origin.strip()
]


# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [

    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    # Static files
    'django.contrib.staticfiles',

    # Project apps
    'users',
    'tasks',
    'dashboard',
]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =========================================================
# URL CONFIGURATION
# =========================================================

ROOT_URLCONF = 'project.urls'


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [

    {
        'BACKEND':
            'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            BASE_DIR / 'templates'
        ],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

                # Study streak and notifications shown in the top
                # bar on every signed in page.

                'dashboard.context_processors.studybuddy_context',

            ],

            # Invalid template variables render as an empty
            # string instead of "None" appearing on the page.

            'string_if_invalid': '',
        },
    },
]


# =========================================================
# WSGI
# =========================================================

WSGI_APPLICATION = 'project.wsgi.application'


# =========================================================
# DATABASE
# =========================================================

DATABASE_URL = os.getenv(
    'DATABASE_URL'
)


# TLS for the database connection.
#
# This defaults to off on purpose. Render hands a service the
# *internal* database URL, which has no sslmode, and its internal
# Postgres does not terminate TLS, so forcing `sslmode=require`
# there would fail the connection. Leaving it off lets psycopg2
# negotiate, which means plain on Render's private network and TLS
# when the server offers it.
#
# A `?sslmode=require` already present in DATABASE_URL is always
# honoured, so Render's *external* connection string still connects
# over TLS without any setting. Set this to True only for a managed
# database that demands encryption.

DATABASE_SSL_REQUIRE = os.getenv(
    'DATABASE_SSL_REQUIRE',
    'False'
).lower() == 'true'


# A local `runserver` has no DATABASE_URL and uses the bundled SQLite
# file. A deployment must be told where its database is, so the
# fallback is off there: Render's disk is ephemeral, and quietly
# running on SQLite would look healthy and then lose every row on the
# next deploy. Setting this variable explicitly overrides the default
# in either direction.

DATABASE_FALLBACK_ENGINE = os.getenv(
    'DATABASE_FALLBACK_ENGINE',
    ''
    if DJANGO_ENV == 'production'
    else 'django.db.backends.sqlite3'
)


# Django's `ManagementUtility.execute` catches ImproperlyConfigured
# while importing these settings, stashes it, and carries on with an
# empty DATABASES. The traceback that finally reaches the build log is
# then "Please supply the ENGINE value", which says nothing about the
# real cause. So every refusal below is written to stderr first, where
# the reason survives, and only then raised to stop the process.

def _refuse(reason):

    sys.stderr.write(
        '\n'
        '=================================================\n'
        ' StudyBuddy cannot start: database not configured\n'
        '=================================================\n'
        f'{reason}\n'
        '=================================================\n\n'
    )

    sys.stderr.flush()

    raise ImproperlyConfigured(reason)


DATABASE_URL_HELP = (
    'A Render PostgreSQL connection string looks like\n'
    '  "postgresql://USER:PASSWORD@HOST:5432/DBNAME"\n'
    'Render fills in DATABASE_URL for you once a PostgreSQL database\n'
    'is linked to the service under Dashboard > Connect.'
)


if DATABASE_URL:

    # `config()` returns an empty dict when DATABASE_URL is unset and
    # raises UnknownSchemeError when the scheme is unrecognised, so
    # neither a missing nor a malformed value is obvious from the
    # settings alone. Resolve it here instead.

    try:

        DATABASES = {

            'default': dj_database_url.config(
                conn_max_age=600,
                conn_health_checks=True,
                ssl_require=DATABASE_SSL_REQUIRE
            )

        }

    except Exception as error:

        _refuse(
            'DATABASE_URL is set but could not be parsed.\n'
            f'  {error}\n'
            f'{DATABASE_URL_HELP}'
        )

    if not DATABASES['default'].get('ENGINE'):

        _refuse(
            'DATABASE_URL is set but produced no database ENGINE, so\n'
            'Django has nothing to connect with.\n'
            f'{DATABASE_URL_HELP}'
        )

elif DATABASE_FALLBACK_ENGINE:

    DATABASES = {

        'default': {

            'ENGINE': DATABASE_FALLBACK_ENGINE,

            'NAME': BASE_DIR / 'db.sqlite3',

        }

    }

else:

    _refuse(
        'DATABASE_URL is not set and the SQLite fallback is switched\n'
        'off for production, because Render\'s disk is ephemeral and a\n'
        'SQLite file there would lose every row on the next deploy.\n'
        f'{DATABASE_URL_HELP}\n'
        'For a deliberate SQLite deployment set\n'
        'DATABASE_FALLBACK_ENGINE=django.db.backends.sqlite3'
    )


# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

]


# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# =========================================================
# STATIC FILES
# =========================================================

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'


# Only use the local static directory if it actually exists.
# This prevents the staticfiles.W004 warning when the folder
# has not been created yet.

STATIC_DIRECTORY = BASE_DIR / 'static'


if STATIC_DIRECTORY.exists():

    STATICFILES_DIRS = [
        STATIC_DIRECTORY
    ]

else:

    STATICFILES_DIRS = []


# The actual staticfiles backend is configured in STORAGES below.
# The legacy STATICFILES_STORAGE setting was removed in Django 5.1,
# so it must not be defined here any more.


# =========================================================
# MEDIA FILES
# =========================================================

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# Only reached when Cloudinary is not configured, which is the
# case for local development.

MEDIA_ROOT.mkdir(
    parents=True,
    exist_ok=True
)


# =========================================================
# CLOUDINARY
# =========================================================

CLOUDINARY_CLOUD_NAME = os.getenv(
    'CLOUDINARY_CLOUD_NAME'
)

CLOUDINARY_API_KEY = os.getenv(
    'CLOUDINARY_API_KEY'
)

CLOUDINARY_API_SECRET = os.getenv(
    'CLOUDINARY_API_SECRET'
)


CLOUDINARY_STORAGE = {

    'CLOUD_NAME':
        CLOUDINARY_CLOUD_NAME,

    'API_KEY':
        CLOUDINARY_API_KEY,

    'API_SECRET':
        CLOUDINARY_API_SECRET,

    'SECURE':
        True,

}


# Only treat Cloudinary as configured when every credential is present.
# Without this check a local install without the env vars would fail on
# every attachment upload instead of falling back to local storage.

CLOUDINARY_IS_CONFIGURED = all(
    [
        CLOUDINARY_CLOUD_NAME,
        CLOUDINARY_API_KEY,
        CLOUDINARY_API_SECRET,
    ]
)


# Configure Cloudinary SDK

cloudinary.config(

    cloud_name=CLOUDINARY_CLOUD_NAME,

    api_key=CLOUDINARY_API_KEY,

    api_secret=CLOUDINARY_API_SECRET,

    secure=True

)


# =========================================================
# DJANGO STORAGE
# =========================================================

if CLOUDINARY_IS_CONFIGURED:

    DEFAULT_FILE_STORAGE_BACKEND = (
        'cloudinary_storage.storage.RawMediaCloudinaryStorage'
    )

else:

    # Local development fallback so attachment uploads keep working
    # without Cloudinary credentials.

    DEFAULT_FILE_STORAGE_BACKEND = (
        'django.core.files.storage.FileSystemStorage'
    )


STORAGES = {

    'default': {

        'BACKEND': DEFAULT_FILE_STORAGE_BACKEND,

    },

    'staticfiles': {

        # The hashed manifest is only useful in production. In debug
        # mode the plain backend keeps missing-file errors away while
        # editing templates.

        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage'
            if not DEBUG
            else 'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),

    },

}


# =========================================================
# DEFAULT PRIMARY KEY
# =========================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =========================================================
# AUTHENTICATION
# =========================================================

LOGIN_URL = 'login'

LOGIN_REDIRECT_URL = 'dashboard'

LOGOUT_REDIRECT_URL = 'login'


# Password reset links must point at the public site, not at
# the request host, because the email is read off-site.

PASSWORD_RESET_TIMEOUT = 60 * 60 * 24


# =========================================================
# EMAIL / RESEND
# =========================================================

RESEND_API_KEY = os.getenv(
    'RESEND_API_KEY'
)


# The Resend backend talks to an HTTP API, so the SMTP settings
# below only apply if EMAIL_BACKEND is overridden to an SMTP
# backend. Without a Resend key, mail is written to the console
# instead of silently disappearing.

if os.getenv('EMAIL_BACKEND'):

    EMAIL_BACKEND = os.getenv('EMAIL_BACKEND')

else:

    if RESEND_API_KEY:

        EMAIL_BACKEND = (
            'users.email_backend.ResendEmailBackend'
        )

    else:

        EMAIL_BACKEND = (
            'django.core.mail.backends.console.'
            'EmailBackend'
        )


EMAIL_HOST = os.getenv(
    'EMAIL_HOST',
    'smtp.resend.com'
)

EMAIL_PORT = int(
    os.getenv(
        'EMAIL_PORT',
        587
    )
)

EMAIL_USE_TLS = (
    os.getenv(
        'EMAIL_USE_TLS',
        'True'
    ).lower() == 'true'
)

EMAIL_HOST_USER = os.getenv(
    'EMAIL_HOST_USER',
    'resend'
)

EMAIL_HOST_PASSWORD = os.getenv(
    'EMAIL_HOST_PASSWORD',
    RESEND_API_KEY
)

DEFAULT_FROM_EMAIL = os.getenv(
    'DEFAULT_FROM_EMAIL',
    'onboarding@resend.dev'
)

# The public address of the site. Password reset links are built
# from it, so the emailed link keeps working when the app is
# reached through a hostname other than the one the form was
# submitted on.

FRONTEND_BASE_URL = os.getenv(
    'FRONTEND_BASE_URL',
    'http://localhost:8000'
).rstrip('/')


EMAIL_TIMEOUT = 20


# =========================================================
# SECURITY SETTINGS FOR PRODUCTION
# =========================================================

if not DEBUG:

    # A weak key in production invalidates sessions, signed cookies
    # and password reset tokens, so fail loudly instead of silently.

    if (
        SECRET_KEY
        == 'django-insecure-development-key'
        or len(SECRET_KEY) < 50
    ):

        raise ImproperlyConfigured(
            'SECRET_KEY is missing or too short. Set a long random '
            'value of at least 50 characters before running with '
            'DEBUG=False.'
        )

    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True

    SECURE_CONTENT_TYPE_NOSNIFF = True

    SECURE_HSTS_SECONDS = 31536000

    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    SECURE_HSTS_PRELOAD = True

    SECURE_PROXY_SSL_HEADER = (
        'HTTP_X_FORWARDED_PROTO',
        'https'
    )

    X_FRAME_OPTIONS = 'DENY'

else:

    # In development `runserver` talks plain HTTP, so forcing a
    # redirect or a secure cookie would lock the developer out.

    SESSION_COOKIE_SECURE = False

    CSRF_COOKIE_SECURE = False

# =========================================================
# FILE UPLOAD LIMIT
# =========================================================

# 50 MB

# 30 MB. NoteForm enforces a 25 MB attachment limit, so this
# leaves headroom for the rest of the multipart body without
# allowing an unbounded request.

DATA_UPLOAD_MAX_MEMORY_SIZE = (
    30 * 1024 * 1024
)

FILE_UPLOAD_MAX_MEMORY_SIZE = (
    30 * 1024 * 1024
)

# Stop oversized POST bodies before they are parsed.

DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000


# =========================================================
# LOGGING
# =========================================================

LOGGING = {

    'version': 1,

    'disable_existing_loggers': False,

    'formatters': {

        'simple': {
            'format': (
                '[{asctime}] {levelname} '
                '{name}: {message}'
            ),
            'style': '{',
        },
    },

    'handlers': {

        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },

    'loggers': {

        'users': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}