"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.1.
"""

import os
from pathlib import Path

from dotenv import load_dotenv

import cloudinary
import dj_database_url


# =========================================================
# BASE DIRECTORY
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# LOAD .ENV
# =========================================================

load_dotenv(
    BASE_DIR / '.env',
    override=True
)


# =========================================================
# SECURITY
# =========================================================

SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-development-key'
)


DEBUG = os.getenv(
    'DEBUG',
    'True'
).lower() == 'true'


ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'studybuddy-9bug.onrender.com',
    'studybuddyapp.in.net',
]


# =========================================================
# CSRF
# =========================================================

CSRF_TRUSTED_ORIGINS = [
    'https://studybuddy-9bug.onrender.com',
    'https://studybuddyapp.in.net',
]


# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [

    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    # Cloudinary
    'cloudinary_storage',
    'cloudinary',

    # Static files
    'django.contrib.staticfiles',

    # Project apps
    'users',
    'tasks',
    'dashboard',
]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =========================================================
# URL CONFIGURATION
# =========================================================

ROOT_URLCONF = 'project.urls'


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [

    {
        'BACKEND':
            'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            BASE_DIR / 'templates'
        ],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]


# =========================================================
# WSGI
# =========================================================

WSGI_APPLICATION = 'project.wsgi.application'


# =========================================================
# DATABASE
# =========================================================

DATABASE_URL = os.getenv(
    'DATABASE_URL'
)


if DATABASE_URL:

    DATABASES = {

        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True
        )

    }

else:

    DATABASES = {

        'default': {

            'ENGINE':
                'django.db.backends.sqlite3',

            'NAME':
                BASE_DIR / 'db.sqlite3',

        }

    }


# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

]


# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# =========================================================
# STATIC FILES
# =========================================================

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'


# Only use the local static directory if it actually exists.
# This prevents the staticfiles.W004 warning when the folder
# has not been created yet.

STATIC_DIRECTORY = BASE_DIR / 'static'


if STATIC_DIRECTORY.exists():

    STATICFILES_DIRS = [
        STATIC_DIRECTORY
    ]

else:

    STATICFILES_DIRS = []


# WhiteNoise storage

STATICFILES_STORAGE = (
    'whitenoise.storage.CompressedManifestStaticFilesStorage'
)


# =========================================================
# MEDIA FILES
# =========================================================

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# =========================================================
# CLOUDINARY
# =========================================================

CLOUDINARY_CLOUD_NAME = os.getenv(
    'CLOUDINARY_CLOUD_NAME'
)

CLOUDINARY_API_KEY = os.getenv(
    'CLOUDINARY_API_KEY'
)

CLOUDINARY_API_SECRET = os.getenv(
    'CLOUDINARY_API_SECRET'
)


CLOUDINARY_STORAGE = {

    'CLOUD_NAME':
        CLOUDINARY_CLOUD_NAME,

    'API_KEY':
        CLOUDINARY_API_KEY,

    'API_SECRET':
        CLOUDINARY_API_SECRET,

    'SECURE':
        True,

}


# Configure Cloudinary SDK

cloudinary.config(

    cloud_name=CLOUDINARY_CLOUD_NAME,

    api_key=CLOUDINARY_API_KEY,

    api_secret=CLOUDINARY_API_SECRET,

    secure=True

)


# =========================================================
# DJANGO STORAGE
# =========================================================

STORAGES = {

    'default': {

        'BACKEND':
            'cloudinary_storage.storage.RawMediaCloudinaryStorage',

    },

    'staticfiles': {

        'BACKEND':
            'whitenoise.storage.CompressedManifestStaticFilesStorage',

    },

}


# =========================================================
# DEFAULT PRIMARY KEY
# =========================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =========================================================
# AUTHENTICATION
# =========================================================

LOGIN_URL = 'login'

LOGIN_REDIRECT_URL = 'dashboard'

LOGOUT_REDIRECT_URL = 'login'


# =========================================================
# EMAIL / RESEND
# =========================================================

EMAIL_BACKEND = (
    'users.email_backend.ResendEmailBackend'
)

EMAIL_HOST = 'smtp.resend.com'

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'resend'

EMAIL_HOST_PASSWORD = os.getenv(
    'RESEND_API_KEY'
)

DEFAULT_FROM_EMAIL = (
    'onboarding@resend.dev'
)

EMAIL_TIMEOUT = 20


# =========================================================
# SECURITY SETTINGS FOR PRODUCTION
# =========================================================

if not DEBUG:

    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True

    SECURE_BROWSER_XSS_FILTER = True

    SECURE_CONTENT_TYPE_NOSNIFF = True

    X_FRAME_OPTIONS = 'DENY'


# =========================================================
# FILE UPLOAD LIMIT
# =========================================================

# 50 MB

DATA_UPLOAD_MAX_MEMORY_SIZE = (
    50 * 1024 * 1024
)

FILE_UPLOAD_MAX_MEMORY_SIZE = (
    50 * 1024 * 1024
)