# Generated by Django 6.1 on 2026-09-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
